### ISSUE TITLE
Setup Google Analytics superProxy

### ISSUE THREAD

**Issue by psiemens** [ubyssey/analytics-dashboard#3]
We need to get our own version of superProxy running so that we can securely access our data from the client side.

**Google Analytics superProxy:** https://developers.google.com/analytics/solutions/google-analytics-super-proxy

This video seems to explain the process fairly well: https://www.youtube.com/watch?time_continue=817&v=8Or8KIhpsqg

Please look into the steps required to get the proxy up and running, and post what you find in this issue.

**Comment by JimFung** [comment]
The google analytics super proxy is up and running! 🎉 🎉 🎉 

We've got 1 query up and running on it right now that returns the # of users for the past day broken down by the hour, you can check that out [here](https://ubyssey-analytics.appspot.com/query?id=ahNzfnVieXNzZXktYW5hbHl0aWNzchULEghBcGlRdWVyeRiAgICAgICACgw&format=json)

We also figured out the structure to the queries we want to run (as posted below). we'll have to add these to the superproxy so that we have public access to them so that'll be the next step. I figured out these queries using the query builder that I linked in the slack chat but I will post them here again just so its properly documented. 

[Google Analytics Query builder](https://ga-dev-tools.appspot.com/query-explorer/)
[Google Analytics Core API Documentation](https://developers.google.com/analytics/devguides/reporting/core/dimsmets)

At the next meeting I can go over in more detail how GASP(Google Analytics Super Proxy, they really missed a marketing opportunity here) works just so we're all on the same page.

*note that the id in the following queries need to be swapped out for the ubyssey's id*
//Total number of sessions sorted by their source for the past 7 days
https://www.googleapis.com/analytics/v3/data/ga?ids=ga%3A114280499&start-date=7daysAgo&end-date=today&metrics=ga%3Asessions&dimensions=ga%3Asource&sort=-ga%3Asource

//Articles sorted by page views for the past 7 days
https://www.googleapis.com/analytics/v3/data/ga?ids=ga%3A114280499&start-date=7daysAgo&end-date=today&metrics=ga%3Apageviews%2Cga%3AuniquePageviews&dimensions=ga%3ApagePath%2Cga%3ApageTitle&sort=-ga%3Apageviews

//Users per hour today
https://www.googleapis.com/analytics/v3/data/ga?ids=ga%3A114280499&start-date=yesterday&end-date=today&metrics=ga%3Ausers&dimensions=ga%3Ahour

**Comment by JimFung** [comment]
The above post is out of date. if you're looking for the queries look at the specific issues!
